services:

  mysql:
    # image: mysql:5.7
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - ./mydata/mysql/data:/var/lib/mysql #数据文件挂载
      - ./mydata/mysql/conf.d:/etc/mysql/conf.d #配置文件挂载
      - ./mydata/mysql/log:/var/log/mysql #日志文件挂载
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  rabbitmq:
      # image: rabbitmq:3.10-management
      build: ./docker/rabbitmq
      container_name: rabbitmq
      volumes:
        - ./mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      ports:
        - 5672:5672
        - 15672:15672
      deploy:
        resources:
          reservations:
            cpus: '0.0001'

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001" #指定数据目录及console运行端口启动
    volumes:
      - ./mydata/minio/data:/data #数据目录挂载
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9090:9000
      - 9001:9001
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./mydata/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - ./mydata/nginx/conf:/etc/nginx #配置文件目录挂载
      - ./mydata/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - ./mydata/nginx/logs:/var/log/nginx #日志文件挂载
    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      - ./mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  logstash:
    image: logstash:7.17.3
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  kibana:
    image: kibana:7.17.3
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  mall-portal:
    image: 192.168.10.61:5000/mall/mall-portal:1.0-SNAPSHOT
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - ./mydata/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  mall-admin:
    image: 192.168.10.61:5000/mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    ports:
      - 8080:8080
    volumes:
      - ./mydata/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    #可以用db这个域名访问mysql服务
    external_links:
      - mysql:db
    deploy:
      resources:
        reservations:
          cpus: '0.0001'

  mall-search:
    image: 192.168.10.61:5000/mall/mall-search:1.0-SNAPSHOT
    container_name: mall-search
    ports:
      - 8081:8081
    volumes:
      - ./mydata/app/mall-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务

          
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8082:8080
