version: "3"

services:
  mall-admin-web:
    image: node:16-buster
    ports:
      - 8090:8090
    volumes:
      - ./mall-admin-web:/app
    working_dir: /app
    # command: sleep infinity
    command: ./entry.sh
    deploy:
      resources:
        limits:
          cpus: "2"
        reservations:
          cpus: "0.01"
          memory: 32M

  mall-app-web:
    image: node:20-buster
    ports:
      - 8088:8088
    volumes:
      - ./app-test-migrate:/app
    working_dir: /app
    # command: sleep infinity
    command: ./entry.sh

    deploy:
      resources:
        limits:
          cpus: "2"
        reservations:
          cpus: "0.01"
          memory: 32M

