version: '3'

services:
  mall-admin-web:
    image: node:14-buster
    ports:
      - 8089:8090
    volumes:
      - ./mall-admin-web:/app
    working_dir: /app
    # command: sleep infinity
    command: ./entry.sh
    deploy:
      resources:
        reservations:
          cpus: '0.0001'
          memory: 32M

  mall-app-web:
    image: node:20-buster
    ports:
      - 8088:8080
    volumes:
      - ./app-test-migrate:/app
    working_dir: /app
    # command: sleep infinity
    command: ./entry.sh

    deploy:
      resources:
        reservations:
          cpus: '0.0001'
          memory: 32M
