spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: reader
    password: 123456
    druid:
      #连接池初始化大小
      initial-size: 5
      #最小空闲连接数
      min-idle: 10
      #最大连接数
      max-active: 20
      web-stat-filter:
        #不统计这些请求数据
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      #访问监控网页的登录用户名和密码
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
    # Redis服务器地址
    host: redis
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 300ms

minio:
  # NOTE: expose to outside for getting image
  #MinIO服务所在地址
  endpoint: http://192.168.10.232:9090
  #存储桶名称
  bucketName: mall
  #访问的key
  accessKey: minioadmin
  #访问的秘钥
  secretKey: minioadmin

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash
